<?php

namespace App\Services\Ai;

use App\Data\AiSettings;

interface AiServiceInterface
{
    /**
     * Send a full message history to the AI service and get a response.
     *
     * @param array $messages The history of messages, each an associative array like ['role' => 'user', 'content' => '...'].
     * @return string The response generated by the AI model.
     */
    public function ask(array $messages, AiSettings $settings): string;
}